severity: error

linters:

  BorderZero:
    enabled: true
    convention: zero

  BemDepth:
    enabled: true

  DeclarationOrder:
    enabled: false

  ExtendDirective:
    enabled: true

  Indentation:
    allow_non_nested_indentation: false
    character: 'tab'
    width: 1

  LeadingZero:
    enabled: false

  NameFormat:
    enabled: true

  PrivateNamingConvention:
    enabled: true
    prefix: _

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
    class_convention: ^(?!js-).*
    class_convention_explanation: should not be written in the form js-*

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  StringQuotes:
    enabled: true

  SelectorDepth:
    enabled: true
    max_depth: 4

  NestingDepth:
    enabled: false